### ISSUE TITLE
Add a module-info.java

### ISSUE THREAD

**Issue by Thihup** [moditect/oss-quickstart#11]

**Comment by gunnarmorling** [comment]
Hey @Thihup, do you mean to archetype resources (so that generated projects will have a module-info.java)? Or to the archetype itself? I suppose the former? If so, we probably make this opt-in via an archetype parameter. WDYT?

**Comment by Thihup** [comment]
Sounds good. Probably having it enabled by default would be great, but having a parameter is ok too.

**Comment by gunnarmorling** [comment]
Ok, pushed something. There's a "moduleName" option now; if set to another value to "NONE", a module descriptor using that module name will be generated; otherwise, no module descriptor will be generated. Feedback welcome (note this archetype isn't published to Maven Central yet, so you'd have to build it from source and install into your local Maven repo).
